apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankaccount-ingress
  namespace: java-quarkus-kafka-bank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  #   kubernetes.io/ingress.class: alb
  #   alb.ingress.kubernetes.io/scheme: internet-facing
  # labels:
  #   app: bankaccount-ingress
spec:
  rules:
    - host: docker.info
    - http:
        paths:
          - path: /transaction-service/*
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
          - path: /balance-service/*
            pathType: Prefix
            backend:
              service:
                name: balance-service
                port:
                  number: 8080
