apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankaccount-ingress
  namespace: java-quarkus-kafka-bank
spec:
  rules:
    - host: docker.info
      http:
        paths:
          - path: /transaction-service/transactions
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
          - path: /balance-service/balances
            pathType: Prefix
            backend:
              service:
                name: balance-service
                port:
                  number: 8081
