apiVersion: v1
kind: Service
metadata:
  name: balance-service
  namespace: java-quarkus-kafka-bank
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: balance-service
    namespace: java-quarkus-kafka-bank

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service
  namespace: java-quarkus-kafka-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-service
      namespace: java-quarkus-kafka-bank
  template:
    metadata:
      labels:
        app: balance-service
        namespace: java-quarkus-kafka-bank
    spec:
      containers:
        - name: balance-service
          image: vitoroc/balance-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          # livenessProbe:
          #   httpGet:
          #     port: 8081
          #     path: /balance-service/health/live
          # readinessProbe:
          #   httpGet:
          #     path: /balance-service/health/ready
          #     port: 8081
