apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: java-quarkus-kafka-bank
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: transaction-service
    namespace: java-quarkus-kafka-bank

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: java-quarkus-kafka-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
      namespace: java-quarkus-kafka-bank
  template:
    metadata:
      labels:
        app: transaction-service
        namespace: java-quarkus-kafka-bank
    spec:
      containers:
        - name: transaction-service
          image: vitoroc/transaction-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /transaction-service/health/live
          readinessProbe:
            httpGet:
              path: /transaction-service/health/ready
              port: 8080
